### ISSUE TITLE
Option to target the Editor only

### ISSUE THREAD

**Issue by ghelton** [jtatum/disable-aa#1]
This is a great plugin, thanks! I'd like to be able to target the editor only. The settings pane doesn't look that great anti aliased.
Currently I'm using this:

```
.editor {
  -webkit-font-smoothing: none;
}
```

**Comment by lazd** [comment]
Just put this in your stylesheet, there's no need for a plugin to do this.

**Comment by jtatum** [comment]
Over two years later, this is fixed in version 0.2 :)
